"""Smart Reporter – LLM-powered readable Markdown report for each CVE.

Consumes the same artifacts as Reporter (state.json + patch_ir.json +
failure.json + events.json + verification.json) and produces a
human-readable CVE_REPORT.md with natural-language analysis.

When an LLM client is available the analysis sections are generated by
the model; otherwise a rule-based template is used.
"""

import json
import os
from datetime import datetime, timezone
from typing import Dict, List, Optional


class SmartReporter:
    def __init__(self, workdir: str, cve_id: str, llm_client=None):
        self.workdir = workdir
        self.cve_id = cve_id
        self.cve_dir = os.path.join(workdir, cve_id)
        self.llm = llm_client

    # ------------------------------------------------------------------
    # public entry points
    # ------------------------------------------------------------------

    def generate_markdown_report(self) -> str:
        """Produce CVE_REPORT.md and return its path."""
        data = self._gather()
        md = self._render(data)
        path = os.path.join(self.cve_dir, "CVE_REPORT.md")
        with open(path, "w", encoding="utf-8") as f:
            f.write(md)
        return path

    def generate_batch_summary_md(self, cve_ids: List[str]) -> str:
        """Produce BATCH_REPORT.md for all CVE IDs."""
        gathered = []
        sections = []
        for cid in cve_ids:
            r = SmartReporter(self.workdir, cid, self.llm)
            data = r._gather()
            gathered.append(data)
            sections.append(r._render_compact(data))
        body = "\n\n---\n\n".join(sections)
        blocker = self._batch_environment_blocker(gathered)
        blocker_text = ""
        if blocker:
            blocker_text = (
                "## Shared Environment Blocker\n\n"
                f"`{blocker['category']}/{blocker['reason_code']}` affected "
                f"{blocker['affected']}/{len(cve_ids)} CVEs before any rewrite attempt. "
                "This batch result does not mean each patch needs manual backporting; "
                "rerun in the target-kernel-matched Docker builder.\n\n---\n\n"
            )
        md = (
            f"# Batch Run Summary\n\n"
            f"**Generated**: {datetime.now(timezone.utc).isoformat()}\n"
            f"**Total CVEs**: {len(cve_ids)}\n\n---\n\n"
            + blocker_text
            + body
        )
        path = os.path.join(self.workdir, "BATCH_REPORT.md")
        with open(path, "w", encoding="utf-8") as f:
            f.write(md)
        return path

    @staticmethod
    def _batch_environment_blocker(items: List[Dict]) -> Optional[Dict]:
        failures = [
            d.get("failure") or {} for d in items
            if (d.get("failure") or {}).get("category") == "env_missing"
        ]
        if len(failures) < 2:
            return None
        keys = [(f.get("category"), f.get("reason_code")) for f in failures]
        key = max(set(keys), key=keys.count)
        affected = keys.count(key)
        if affected < 2:
            return None
        return {"category": key[0], "reason_code": key[1], "affected": affected}

    # ------------------------------------------------------------------
    # data gathering
    # ------------------------------------------------------------------

    def _gather(self) -> Dict:
        return {
            "cve_id": self.cve_id,
            "state": self._read_json("state.json"),
            "patch_ir": self._read_json("patch_ir.json", {}),
            "failure": self._read_json("failure.json"),
            "verification": self._read_json("verification.json", {}),
            "events": self._read_json("events.json", []),
            "report": self._read_json("report.json", {}),
        }

    # ------------------------------------------------------------------
    # rendering
    # ------------------------------------------------------------------

    def _render(self, d: Dict) -> str:
        state = d["state"]
        patch_ir = d["patch_ir"]
        failure = d["failure"]
        verification = d["verification"]
        events = d["events"]
        status = state.get("status", "unknown")

        lines = [
            f"# CVE Report: {self.cve_id}",
            "",
            f"**Status**: `{status}` | **Attempts**: {state.get('attempt', 0)}/{state.get('max_attempts', 5)}",
            f"**Kernel**: {self._kver()} | **Generated**: {datetime.now(timezone.utc).isoformat()}",
            "",
        ]

        lines.append("## Executive Summary")
        lines.append("")
        lines.append(self._exec_summary(d))
        lines.append("")

        lines.append("## Pipeline Timeline")
        lines.append("")
        lines.append("| Step | From | To | Reason |")
        lines.append("|------|------|----|--------|")
        for e in events[-15:]:
            lines.append(
                f"| | {e.get('from')} | {e.get('to')} | {e.get('reason', '')} |"
            )
        lines.append("")

        lines.append("## Patch Analysis")
        lines.append("")
        files = patch_ir.get("files", [])
        funcs = patch_ir.get("functions", [])
        risk_tags = patch_ir.get("risk_tags", [])
        if files:
            lines.append("### Modified Files")
            for f in files:
                lines.append(
                    f"- `{f.get('path', '?')}` ({f.get('status', '?')}, "
                    f"{f.get('hunk_count', 0)} hunks)"
                )
            lines.append("")
        if funcs:
            lines.append("### Affected Functions")
            for fn in funcs:
                tags = ", ".join(fn.get("risk_tags", []) or ["none"])
                lines.append(
                    f"- `{fn.get('name', '?')}` @ `{fn.get('file', '?')}`"
                    f" -- risk: {tags}"
                )
            lines.append("")
        if risk_tags:
            lines.append(f"**Risk Tags**: {', '.join(risk_tags)}")
            lines.append("")
        lines.append(
            f"**Semantic Summary**: {patch_ir.get('semantic_summary', 'N/A')}"
        )
        lines.append("")

        if failure:
            lines.append("## Failure Analysis")
            lines.append("")
            lines.append("| Field | Value |")
            lines.append("|-------|-------|")
            lines.append(f"| Category | `{failure.get('category', '?')}` |")
            lines.append(f"| Reason Code | `{failure.get('reason_code', '?')}` |")
            lines.append(f"| Summary | {failure.get('summary', '?')} |")
            lines.append(f"| Next Action | `{failure.get('next_action', '?')}` |")
            lines.append("")
            lines.append(self._failure_analysis(d))
            lines.append("")

        lines.append("## Verification")
        lines.append("")
        if verification:
            lines.append("| Field | Value |")
            lines.append("|-------|-------|")
            for k, v in verification.items():
                lines.append(f"| {k} | {v} |")
        else:
            lines.append(
                "No verification performed (build did not produce a valid .ko)."
            )
        lines.append("")

        artifact = d["report"].get("artifact", {}) or {}
        ko_path = artifact.get("path")
        lines.append("## Artifact")
        lines.append("")
        if ko_path:
            lines.append(f"- **.ko path**: `{ko_path}`")
            lines.append(f"- **SHA256**: `{artifact.get('sha256', 'N/A')}`")
        else:
            lines.append("No livepatch module produced.")
        lines.append("")

        lines.append("## Recommendation")
        lines.append("")
        lines.append(self._recommendation(d))
        lines.append("")

        return "\n".join(lines)

    def _render_compact(self, d: Dict) -> str:
        state = d["state"]
        status = state.get("status", "unknown")
        failure = d["failure"]
        patch_ir = d["patch_ir"]

        lines = [
            f"## {d['cve_id']} -- `{status}`",
            "",
            f"- **State**: {state.get('state', '?')} | "
            f"**Attempts**: {state.get('attempt', 0)}",
            f"- **Files**: {', '.join(f.get('path', '?') for f in patch_ir.get('files', []))}",
            f"- **Semantic**: {patch_ir.get('semantic_summary', 'N/A')}",
        ]
        if failure:
            lines.append(
                f"- **Failure**: `{failure.get('category')}/{failure.get('reason_code')}`"
                f" -- {failure.get('summary', '')}"
            )
        lines.append("")
        lines.append(self._exec_summary(d))
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # LLM / rule helpers
    # ------------------------------------------------------------------

    def _exec_summary(self, d: Dict) -> str:
        if self.llm:
            return self._llm_section(d, "exec_summary")
        return self._rule_exec_summary(d)

    def _failure_analysis(self, d: Dict) -> str:
        if self.llm:
            return self._llm_section(d, "failure_analysis")
        return self._rule_failure_analysis(d)

    def _recommendation(self, d: Dict) -> str:
        if self.llm:
            return self._llm_section(d, "recommendation")
        return self._rule_recommendation(d)

    def _llm_section(self, d: Dict, section: str) -> str:
        prompts = {
            "exec_summary": (
                "You are a kernel security analyst. Write a 3-5 sentence executive "
                "summary of the livepatch pipeline result for this CVE. Include: what "
                "the CVE is about, what happened during the pipeline, the final "
                "outcome, and the key takeaway.\n\n"
            ),
            "failure_analysis": (
                "You are a kernel build engineer. Analyze the failure below and "
                "explain in 2-4 sentences WHY this specific failure occurred, what "
                "it means, and whether it is expected or surprising.\n\n"
            ),
            "recommendation": (
                "You are a kernel livepatch expert. Based on the pipeline result, "
                "give a 2-4 sentence recommendation for next steps. Be specific: "
                "should the patch be manually rewritten, is the kernel version "
                "incompatible, or is a workaround available?\n\n"
            ),
        }
        prompt = prompts.get(section, prompts["exec_summary"])
        prompt += (
            f"```json\n"
            f"{json.dumps(self._llm_context(d), indent=2, ensure_ascii=False)}\n"
            f"```\n"
        )
        prompt += "\nRespond in Chinese, 3-5 sentences only. No markdown formatting."

        try:
            resp = self.llm.chat([{"role": "user", "content": prompt}])
            return resp.strip()
        except Exception:
            pass
        fallbacks = {
            "exec_summary": self._rule_exec_summary,
            "failure_analysis": self._rule_failure_analysis,
            "recommendation": self._rule_recommendation,
        }
        return fallbacks.get(section, self._rule_exec_summary)(d)

    def _llm_context(self, d: Dict) -> Dict:
        return {
            "cve_id": d["cve_id"],
            "status": d["state"].get("status", "unknown"),
            "state": d["state"].get("state", ""),
            "attempts": d["state"].get("attempt", 0),
            "patch_ir": {
                "files": [f.get("path") for f in d["patch_ir"].get("files", [])],
                "functions": [
                    f.get("name") for f in d["patch_ir"].get("functions", [])
                ],
                "risk_tags": d["patch_ir"].get("risk_tags", []),
                "semantic_summary": d["patch_ir"].get("semantic_summary", ""),
            },
            "failure": d["failure"],
            "verification": d["verification"],
            "events": [
                {"from": e.get("from"), "to": e.get("to"), "reason": e.get("reason")}
                for e in d["events"][-8:]
            ],
        }

    # ------------------------------------------------------------------
    # rule-based fallbacks
    # ------------------------------------------------------------------

    def _rule_exec_summary(self, d: Dict) -> str:
        state = d["state"]
        status = state.get("status", "unknown")
        patch_ir = d["patch_ir"]
        failure = d["failure"]

        funcs = [f.get("name", "?") for f in patch_ir.get("functions", [])]
        files = [f.get("path", "?") for f in patch_ir.get("files", [])]

        if status == "success":
            return (
                f"该 CVE 补丁已成功构建并验证。涉及 {len(files)} 个文件、"
                f"{len(funcs)} 个函数，"
                f"补丁语义：{patch_ir.get('semantic_summary', 'N/A')}。"
                f"热补丁模块可在目标内核上正常加载和卸载。"
            )
        if status == "skipped":
            return (
                f"该 CVE 补丁已被合入目标内核源码树，跳过热补丁构建。"
                f"三阶段检查确认补丁已存在于内核中，无需重复构建。"
            )
        if status == "manual_required":
            cat = failure.get("category", "unknown") if failure else "unknown"
            code = failure.get("reason_code", "?") if failure else "?"
            if cat == "env_missing":
                return (
                    f"该 CVE 补丁已进入构建前检查，但被共享构建环境问题 "
                    f"{cat}/{code} 阻断。尚未进行自动改写；"
                    f"请在与目标内核匹配的 Docker 构建环境中重新运行。"
                )
            return (
                f"该 CVE 补丁在自动流水线中未能成功产出热补丁模块。"
                f"涉及 {len(files)} 个文件、{len(funcs)} 个函数。"
                f"失败类别：{cat}/{code}，"
                f"经 {state.get('attempt', 0)} 轮改写尝试后仍需人工介入。"
            )
        return (
            f"该 CVE 流水线执行完毕，最终状态为 {status}。"
            f"涉及 {len(files)} 个文件的修改。"
        )

    def _rule_failure_analysis(self, d: Dict) -> str:
        failure = d.get("failure") or {}
        cat = failure.get("category", "unknown")
        code = failure.get("reason_code", "unknown")

        analyses = {
            ("compile", "api_mismatch"): (
                "补丁中修改的函数签名与目标内核不匹配。"
                "目标内核版本与补丁原始版本之间存在 API 变更。"
                "需要手动调整函数调用参数以匹配目标内核的 ABI。"
            ),
            ("compile", "missing_api_or_include"): (
                "补丁引用了目标内核中不存在或位置不同的符号/头文件。"
                "需要查找目标内核中对应的 API 并更新 include 路径或符号名称。"
            ),
            ("compile", "field_mismatch"): (
                "补丁访问的结构体字段在目标内核中不存在或类型不同。"
                "目标内核版本的结构体布局与补丁预期不一致，需要手动适配。"
            ),
            ("kpatch_limit", "no_fentry"): (
                "目标函数缺少 fentry 插桩点，kpatch 无法对该函数进行热补丁。"
                "这是内核编译选项限制，无法通过改写补丁解决。"
            ),
            ("kpatch_limit", "struct_or_data_change"): (
                "补丁涉及结构体定义修改或静态数据变更，kpatch 不支持此类热补丁。"
                "需要评估是否可以通过函数级别的替代方案实现修复。"
            ),
            ("patch_apply", "hunk_failed"): (
                "补丁无法干净应用到目标内核源码，存在上下文漂移（context drift）。"
                "内核文件在补丁目标区域附近有其他修改，导致 hunk 匹配失败。"
                "可尝试调整补丁的上下文行或使用更高 fuzz 因子。"
            ),
        }

        key = (cat, code)
        if key in analyses:
            return analyses[key]
        return (
            f"构建失败，失败类别为 {cat}，具体原因代码为 {code}。"
            f"失败摘要：{failure.get('summary', '无详细信息')}。"
            f"建议查看构建日志获取完整错误信息。"
        )

    def _rule_recommendation(self, d: Dict) -> str:
        state = d["state"]
        failure = d.get("failure") or {}
        status = state.get("status", "unknown")

        if status == "success":
            return (
                "热补丁模块已就绪。建议：1) 在更多测试 VM 上验证兼容性；"
                "2) 进行压力测试确认模块稳定性；3) 准备回滚方案后部署到生产环境。"
            )
        if status == "skipped":
            return (
                "该补丁已在内核中，无需额外操作。"
                "建议定期扫描 CVE 公告以保持内核安全更新。"
            )
        if status == "manual_required":
            cat = failure.get("category", "")
            code = failure.get("reason_code", "")
            if cat == "env_missing":
                return (
                    f"该结果属于构建环境阻断（{cat}/{code}），不是补丁改写失败。"
                    "请使用固定目标 GCC、kpatch-build 和 vmlinux 的 Docker 构建环境重新运行。"
                )
            if (cat, code) in [
                ("kpatch_limit", "no_fentry"),
                ("kpatch_limit", "struct_or_data_change"),
            ]:
                return (
                    "该 CVE 不适合热补丁修复。建议：1) 评估是否可通过 kprobe/"
                    "其他 hook 机制缓解；2) 安排内核版本升级以包含修复；"
                    "3) 在不支持的场景中记录例外处理。"
                )
            if cat == "patch_apply":
                return (
                    "需要手动调整补丁以适配目标内核。建议：1) 检查目标内核文件中"
                    "补丁区域的代码差异；2) 手动调整 hunk 上下文；"
                    "3) 重新生成补丁后重新运行流水线。"
                )
            if cat == "compile":
                return (
                    "需要手动修复编译错误。建议：1) 查看构建日志确定具体错误行；"
                    "2) 根据目标内核 API 调整代码；"
                    "3) 在本地验证编译通过后更新补丁。"
                )
            return (
                f"需要人工介入处理 {cat}/{code} 类型失败。"
                f"请查看 failure.json 获取详细信息。"
            )
        return "请查看完整报告和日志以确定下一步操作。"

    # ------------------------------------------------------------------
    # helpers
    # ------------------------------------------------------------------

    def _read_json(self, filename: str, default=None):
        path = os.path.join(self.cve_dir, filename)
        if not os.path.exists(path):
            return default if default is not None else {}
        with open(path) as f:
            return json.load(f)

    def _kver(self) -> str:
        rc = self._read_json(os.path.join(self.workdir, "run_config.json"))
        return rc.get("kernel_version", "6.6.102-5.2.an23.x86_64")
